Bug 42468: Add systemd support for OCLC Connexion daemon
Koha ships an OCLC Connexion import daemon that listens for connections
from OCLC Connexion client or WorldShare Record Manager and creates
records in Koha. The daemon was never bundled into the koha packaging
with a helper script and an init unit, so sites using Connexion have
had to roll their own service files and manage the daemon manually.

This patch adds Connexion to the same backend-dispatching framework
bug 40901 introduced for SIP/Plack/Zebra/etc. so it can be enabled,
disabled, started, stopped, restarted, and queried with one via
koha-connexion for both sysv and systemd. I've used SIP as the
pattern because it is also an optional component that doesn't
get started by default.

Test Plan:
1) Apply this patch and rebuild the koha packages
2) Pick an instance you can test against ( e.g. kohadev )
3) Create /etc/koha/sites/kohadev/connexion.conf such as:
     port: 5500
     koha: http://localhost:8080
     user: koha
     password: koha
4) Run: koha-connexion --enable kohadev
5) Run: koha-connexion --start kohadev
6) Run: koha-connexion --status kohadev
7) Note that the daemon is running
8) Run systemctl status koha-connexion@kohadev.service
9) Note that systemd reports the daemon as active!
8) Telnet to port 5500
   For bonus points, send an valid connex message
10) Run koha-connexion --restart kohadev
11) Note that the daemon restarts cleanly
12) Run koha-list --connexion
13) Note kohadev is listed
14) Runkoha-list --noconnexion
15) Note that kohadev is not listed
12) Run koha-connexion --disable kohadev
13) Note that the daemon is stopped and disabled
14) Re-enable, then disable the entire instance:
      koha-connexion --enable kohadev
      koha-connexion --start kohadev
      koha-disable kohadev
15) Note that the Connexion daemon is also stopped and disabled

Signed-off-by: Kyle M Hall <kyle@bywatersolutions.com>

diff --git a/debian/scripts/koha-list b/debian/scripts/koha-list
--- a/debian/scripts/koha-list
+++ b/debian/scripts/koha-list
@@ -60,6 +60,7 @@ filter_ok()
        instance_filter_letsencrypt   $instance && \
        instance_filter_plack         $instance && \
        instance_filter_z3950         $instance && \
+       instance_filter_connexion     $instance && \
        instance_filter_sip           $instance; then
         return 0;
     else
@@ -80,6 +81,27 @@ instance_filter_sip()
             fi ;;
         "disabled")
             if ! is_sip_enabled $instance; then
+                return 0
+            fi ;;
+    esac
+
+    # Didn't match any criteria
+    return 1
+}
+
+instance_filter_connexion()
+{
+    local instance=$1
+
+    case $show_connexion in
+        "all")
+            return 0 ;;
+        "enabled")
+            if is_connexion_enabled $instance; then
+                return 0
+            fi ;;
+        "disabled")
+            if ! is_connexion_enabled $instance; then
                 return 0
             fi ;;
     esac
@@ -259,6 +281,17 @@ set_show_sip()
     fi
 }
 
+set_show_connexion()
+{
+    local connexion_param=$1
+
+    if [ "$show_connexion" = "all" ]; then
+        show_connexion=$connexion_param
+    else
+        die "Error: --connexion and --noconnexion are mutually exclusive."
+    fi
+}
+
 set_show_z3950()
 {
     local z3950_param=$1
@@ -288,6 +321,8 @@ Options:
     --noemail         Show instances with email disabled
     --sip             Show instances with SIP enabled
     --nosip           Show instances with SIP disabled
+    --connexion       Show instances with Connexion daemon enabled
+    --noconnexion     Show instances with Connexion daemon disabled
     --plack           Show instances with Plack enabled
     --noplack         Show instances with Plack disabled
     --letsencrypt     Show instances with letsencrypt enabled
@@ -305,11 +340,12 @@ show="all"
 show_elasticsearch="all"
 show_email="all"
 show_sip="all"
+show_connexion="all"
 show_plack="all"
 show_letsencrypt="all"
 show_z3950="all"
 
-args=$(getopt -l help,enabled,disabled,elasticsearch,noelasticsearch,email,noemail,sip,nosip,plack,noplack,letsencrypt,noletsencrypt,z3950,noz3950 -o h -n $0 -- "$@")
+args=$(getopt -l help,enabled,disabled,elasticsearch,noelasticsearch,email,noemail,sip,nosip,connexion,noconnexion,plack,noplack,letsencrypt,noletsencrypt,z3950,noz3950 -o h -n $0 -- "$@")
 set -- $args
 
 while [ ! -z "$1" ]
@@ -320,6 +356,8 @@ do
         --noemail) set_show_email "disabled" ;;
             --sip) set_show_sip "enabled" ;;
           --nosip) set_show_sip "disabled" ;;
+      --connexion) set_show_connexion "enabled" ;;
+    --noconnexion) set_show_connexion "disabled" ;;
           --plack) set_show_plack "enabled" ;;
         --noplack) set_show_plack "disabled" ;;
     --letsencrypt) set_show_letsencrypt "enabled" ;;
